# Generated by Django 5.2.4 on 2025-08-03 06:59

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_alter_tag_options_alter_category_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=300, unique=True)),
                ('sub_title', models.CharField(blank=True, db_index=True, max_length=300, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=400, null=True, unique=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses')),
                ('is_free', models.BooleanField(default=True)),
                ('price_type', models.CharField(choices=[('free', 'Free'), ('uzs', "🇺🇿 So'm"), ('rub', '₽ Rubl'), ('eur', '€ Yevro'), ('usd', '$ AQSh dollari')], default='free', max_length=10)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('language', models.CharField(choices=[('uz', "O'zbek"), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=10)),
                ('duration', models.CharField(choices=[('1m', '1 oylik'), ('3m', '3 oylik'), ('6m', '6 oylik'), ('1y', '1 yillik')], default='1m', max_length=10)),
                ('students_count', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('category', models.ForeignKey(limit_choices_to={'role': 'course'}, on_delete=django.db.models.deletion.CASCADE, related_name='course_category', to='category.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='course_tags', to='category.tag')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='course_teacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=300, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=400, null=True, unique=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lesson_images')),
                ('file', models.FileField(blank=True, null=True, upload_to='lesson_files')),
                ('video', models.FileField(blank=True, null=True, upload_to='lesson_videos')),
                ('duration', models.DurationField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=300, null=True)),
                ('views_count', models.IntegerField(default=0)),
                ('is_preview', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_course', to='course.course')),
                ('tags', models.ManyToManyField(blank=True, related_name='lesson_tags', to='category.tag')),
            ],
            options={
                'verbose_name': 'Video dars',
                'verbose_name_plural': 'Video darslar',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('rate', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_course', to='course.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
