# Generated by Django 5.2.4 on 2025-08-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
    ]
