# Generated by Django 5.2.4 on 2025-08-05 18:29

import ckeditor.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(db_index=True, help_text='Telefon raqamingizni kiriting: ', max_length=15, region='UZ')),
                ('link', models.URLField(blank=True, null=True)),
                ('subject', models.CharField(db_index=True, max_length=100)),
                ('message', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Biz bilan aloqa!',
                'verbose_name_plural': 'Biz bilan aloqa!',
            },
        ),
    ]
