# Generated by Django 5.2.4 on 2025-08-30 19:10

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, help_text='Telefon raqamingizni kiriting: ', max_length=20, region='UZ'),
        ),
    ]
