# Generated by Django 5.2.4 on 2025-08-01 16:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
