# Generated by Django 5.2.4 on 2025-08-03 07:51

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, help_text='Telefon raqamingizni kiriting: ', max_length=15, region='UZ', unique=True),
        ),
    ]
