# Generated by Django 5.2.4 on 2025-08-01 16:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subemail',
            options={'verbose_name': 'SubEmail', 'verbose_name_plural': 'SubEmails'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subemail',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
