# Generated by Django 5.2.4 on 2025-08-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subemail',
            name='telegram_username',
            field=models.URLField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
