# Generated by Django 5.2.4 on 2025-08-03 07:51

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_subemail_telegram_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subemail',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, default=0, help_text='Telefon raqamingiz, masalan: +998901234567', max_length=15, region='UZ', unique=True),
            preserve_default=False,
        ),
    ]
