# Generated by Django 5.2.4 on 2025-08-02 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='bio',
            new_name='description',
        ),
    ]
