# Generated by Django 5.2.4 on 2025-08-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_rename_bio_article_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
